name: ChatGPT v3
on:
  workflow_dispatch:
    inputs:
      KERNEL_SOURCE:
        description: 'Kernel source URL'
        required: true
        default: 'https://github.com/AnymoreProject/kernel_xiaomi_vayu_upstream.git'
      KERNEL_BRANCH:
        description: 'Kernel branch'
        required: true
        default: 'ksu'
      KERNEL_NAME:
        description: 'Kernel/zip name'
        required: true
        default: 'AnymoreKSU'
      CONFIG_FILE:
        description: 'Config file (multiple configs separated by space)'
        required: true
        default: 'vayu_defconfig'
      TOOLCHAIN_URL:
        description: "Toolchain URL including branch"
        required: true
        default: 'https://gitlab.com/crdroidandroid/android_prebuilts_clang_host_linux-x86_clang-r536225.git -b 15.0'
      ANYKERNEL:
        description: "AnyKernel URL including branch"
        required: true
        default: 'https://github.com/AnymoreProject/AnyKernel3.git -b master'

jobs:
  Kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        run: |
          # Clear workspace and install dependencies
          rm -rf ${{ github.workspace }}/*
          sudo apt-get update && sudo apt-get install -y \
            build-essential bc lld gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi \
            libssl-dev libfl-dev llvm curl git ftp lftp wget \
            libarchive-tools ccache python2 python2-dev \
            zip unzip tar gzip bzip2 rar unrar cpio jq

      - name: Clone Kernel Source
        run: |
          # Clone the specified kernel source repository
          git clone --single-branch --depth=1 --no-tags ${{ github.event.inputs.KERNEL_SOURCE }} -b ${{ github.event.inputs.KERNEL_BRANCH }} ${{ github.workspace }}

      - name: Clone Toolchain
        run: |
          TOOLCHAIN_DIR="${{ github.workspace }}/toolchain"
          mkdir -p "${TOOLCHAIN_DIR}"
          TOOLCHAIN_URL="${{ github.event.inputs.TOOLCHAIN_URL }}"
          
          # Extracting the branch if specified
          if [[ "$TOOLCHAIN_URL" == *"-b "* ]]; then
            BRANCH=${TOOLCHAIN_URL##*-b }
            REPO_URL=${TOOLCHAIN_URL%-b *}  # Get URL without the branch
            git clone --single-branch --depth=1 --no-tags "$REPO_URL" -b "$BRANCH" "$TOOLCHAIN_DIR"
          else
            if [[ "$TOOLCHAIN_URL" == *.tar.gz ]]; then
              wget -O "${TOOLCHAIN_DIR}/toolchain.tar.gz" "$TOOLCHAIN_URL"
              tar -xzf "${TOOLCHAIN_DIR}/toolchain.tar.gz" -C "${TOOLCHAIN_DIR}" --strip-components=1
            elif [[ "$TOOLCHAIN_URL" == *.zip ]]; then
              wget -O "${TOOLCHAIN_DIR}/toolchain.zip" "$TOOLCHAIN_URL"
              unzip -d "${TOOLCHAIN_DIR}" "${TOOLCHAIN_DIR}/toolchain.zip"
            else
              git clone --single-branch --depth=1 --no-tags "$TOOLCHAIN_URL" "$TOOLCHAIN_DIR"
            fi
          fi


      - name: Set up Cache
        id: cache-out
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/out
          key: ${{ github.event.inputs.KERNEL_SOURCE }}-${{ github.event.inputs.KERNEL_BRANCH }}-out

      - name: Start Compilation
        run: |
          # Set up environment variables
          objdir="${{ github.workspace }}/out"
          anykernel="${{ github.workspace }}/anykernel"
          clang_dir="${{ github.workspace }}/toolchain"
          kernel_name="${{ github.event.inputs.KERNEL_NAME }}"
          zip_name="${kernel_name}-$(date +"%d-%m-%Y").zip"
          arch="arm64"
          export PATH="${clang_dir}/bin:$PATH"

          # Function to configure the kernel
          make_defconfig() {
            echo "Configuring kernel with ${CONFIG_FILE}..."
            make -s ARCH=${arch} O=${objdir} ${{ github.event.inputs.CONFIG_FILE }} -j$(nproc --all)
          }

          # Function to compile the kernel
          compile() {
            echo "Compiling kernel..."
            cd "${{ github.workspace }}"
            make -j$(nproc --all) \
              O=${objdir} \
              ARCH=${arch} \
              CC=clang \
              CROSS_COMPILE=aarch64-linux-gnu- \
              CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
              CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
              AR=llvm-ar \
              LLVM_NM=llvm-nm \
              OBJCOPY=llvm-objcopy \
              LD=ld.lld \
              NM=llvm-nm \
              LLVM=1 \
              LLVM_IAS=1
          }

          # Function to prepare the AnyKernel package
          completion() {
            cd "${objdir}"
            compiled_image="arch/arm64/boot/Image"
            compiled_dtbo="arch/arm64/boot/dtbo.img"
            qcom_dtb="arch/arm64/boot/dts/vendor/qcom"

            if [[ -f ${compiled_image} && -f ${compiled_dtbo} ]]; then
              echo "Preparing AnyKernel package..."
              git clone -q ${{ github.event.inputs.ANYKERNEL }} "$anykernel"
              cp "${compiled_image}" "${{ github.workspace }}"
              cp "${compiled_dtbo}" "${{ github.workspace }}"

              if ls ${qcom_dtb}/*.dtb 1> /dev/null 2>&1; then
                cp ${qcom_dtb}/*.dtb "${{ github.workspace }}"
              fi

              mv -f "${compiled_image}" "$anykernel/Image"
              mv -f "${compiled_dtbo}" "$anykernel/dtbo.img"
              cd "$anykernel"
              zip -r AnyKernel.zip *
              mv -- "AnyKernel.zip" "${{ github.workspace }}/$zip_name"
              rm -rf "$anykernel"
              echo "Build completed successfully."
            else
              echo "ERROR: Kernel compilation failed!"
              exit 1
            fi
          }

          # Execute the functions
          make_defconfig
          compile
          completion

          # Set up file info for release
          cd "${{ github.workspace }}"
          zip_file=$(find . -name '${{ github.event.inputs.KERNEL_NAME }}*.zip' -print -quit)
          echo "ZIP_FILE=$zip_file" >> $GITHUB_ENV
          echo "ZIP_NAME=$(basename "$zip_file" .zip)" >> $GITHUB_ENV
          echo "RELEASE_DATE=$(date +'%B %-d, %Y %H:%M')" >> $GITHUB_ENV
          echo "DTBO=${{ github.workspace }}/dtbo.img" >> $GITHUB_ENV
          echo "IMAGE=${{ github.workspace }}/Image" >> $GITHUB_ENV

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/*.dtb
            ${{ github.workspace }}/${{ github.event.inputs.KERNEL_NAME }}*.zip
            ${{ github.workspace }}/dtbo.img
            ${{ github.workspace }}/Image
          name: ${{ github.event.inputs.KERNEL_NAME }} Release
          tag_name: ${{ github.run_id }}
          body: |
            Released on $(TZ='Asia/Kuala_Lumpur' date +"%B %-d, %Y %H:%M")
